services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: order_service
    ports:
      - "3309:3306"
    volumes:
      - ./mysql:/var/lib/mysql