version: '4'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_inventory_service
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql
